# Debugging image_to_neo_exporter

In [1]:
import neo4j
import numpy as np
from image_to_neo_exporter import ImageNeoExporter

In [2]:
neo4j_url = "bolt://localhost:7687"
neo4j_password = "your_password"
neo4j_user = "neo4j"
exporter = ImageNeoExporter(neo4j_url, neo4j_user, neo4j_password)

In [3]:
image = np.tril(np.triu(np.ones((5,5),int),1),1)

print(image)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [4]:
exporter.export_image(image)
exporter.close()

Generated: (p00:Pixel {v: 0, y: 0, x:0}), (p01:Pixel {v: 1, y: 0, x:1}), (p02:Pixel {v: 0, y: 0, x:2}), (p03:Pixel {v: 0, y: 0, x:3}), (p04:Pixel {v: 0, y: 0, x:4}), (p10:Pixel {v: 0, y: 1, x:0}), (p11:Pixel {v: 0, y: 1, x:1}), (p12:Pixel {v: 1, y: 1, x:2}), (p13:Pixel {v: 0, y: 1, x:3}), (p14:Pixel {v: 0, y: 1, x:4}), (p20:Pixel {v: 0, y: 2, x:0}), (p21:Pixel {v: 0, y: 2, x:1}), (p22:Pixel {v: 0, y: 2, x:2}), (p23:Pixel {v: 1, y: 2, x:3}), (p24:Pixel {v: 0, y: 2, x:4}), (p30:Pixel {v: 0, y: 3, x:0}), (p31:Pixel {v: 0, y: 3, x:1}), (p32:Pixel {v: 0, y: 3, x:2}), (p33:Pixel {v: 0, y: 3, x:3}), (p34:Pixel {v: 1, y: 3, x:4}), (p40:Pixel {v: 0, y: 4, x:0}), (p41:Pixel {v: 0, y: 4, x:1}), (p42:Pixel {v: 0, y: 4, x:2}), (p43:Pixel {v: 0, y: 4, x:3}), (p44:Pixel {v: 0, y: 4, x:4}), (p00)-[:RIGHT]->(p01), (p00)-[:BOTTOM]->(p10), (p01)-[:RIGHT]->(p02), (p01)-[:BOTTOM]->(p11), (p01)-[:LEFT]->(p00), (p02)-[:RIGHT]->(p03), (p02)-[:BOTTOM]->(p12), (p02)-[:LEFT]->(p01), (p03)-[:RIGHT]->(p04), (p03)-